{% set name = "bgcflow_wrapper" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bgcflow_wrapper-{{ version }}.tar.gz
  sha256: deb81503d8a7c328aef19aec4fd170c63cbc6009ccce247c5e79f7423558ebfe

build:
  entry_points:
    - bgcflow = bgcflow.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - pytest >=7.2.0
    - mkdocs-material >=9.2.0,<10.0.0
    - click >=8.1.3,<9.0.0
    - snakedeploy >=0.8.2,<0.9.0
    - peppy >=0.35.4,<0.36.0
    - panoptes-ui >=0.2.0,<0.3.0
    - snakemake >=7.18.2,<8.0.0
    - mkdocs-jupyter >=0.24.2,<0.25.0
    - mkdocs-macros-plugin >=1.0.4,<2.0.0
    - setuptools >=65.5.1,<66.0.0
    - numpy >=1.22.0
    - sqlalchemy 1.4.46
    - gitpython >=3.1.35,<4.0.0
    - dbt-metabase >=0.9.15,<0.10.0
    - pandas <2.1.0
    - mkdocs-material-extensions >=1.0.3,<2.0.0
    - livereload >=2.6.3,<3.0.0
    - pyreadline >=2.1,<3.0
  run_constrained:
    - black >=22.3.0,<23.0.0
    - isort 5.10.1
    - flake8 4.0.1
    - flake8-docstrings >=1.6.0,<2.0.0
    - pytest-cov >=3.0.0,<4.0.0
    - virtualenv >=20.13.1,<21.0.0
    - pip >=22.0.3,<23.0.0
    - mkdocs >=1.2.3,<2.0.0
    - mkdocs-include-markdown-plugin >=3.2.3,<4.0.0
    - mkdocstrings >=0.18.0,<0.19.0
    - mkdocs-material-extensions >=1.0.3,<2.0.0
    - twine >=3.8.0,<4.0.0
    - mkdocs-autorefs >=0.3.1,<0.4.0
    - pre-commit >=2.17.0,<3.0.0
    - toml >=0.10.2,<0.11.0
    - livereload >=2.6.3,<3.0.0
    - pyreadline >=2.1.0,<3.0.0
    - mike >=1.1.2,<2.0.0
    - tox >=4.6.4,<5.0.0

test:
  imports:
    - bgcflow_wrapper
  commands:
    - pip check
    - bgcflow --help
  requires:
    - pip

about:
  home: https://github.com/NBChub/bgcflow_wrapper
  summary: A snakemake wrapper and utility tools command line interface for BGCFlow.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matinnuhamunada
